on: [push]
name: build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.4.4' # Exact version of ghc to use
          enable-stack: true
          stack-version: 'latest'
      - name: Install dependencies
        run: sudo apt-get install -y libgd3 libgd-dev
      - run: stack build
